# Changes here will be overwritten by Copier
_commit: 0.1.15
_src_path: gh:12rambau/pypackage
author_email: pierrick.rambaud49@gmail.com
author_first_name: Pierrick
author_last_name: Rambaud
author_orcid: 0000-0001-8764-5749
creation_year: "2023"
github_repo_name: pygaul
github_user: gee-community
project_name: pyGAUL
project_slug: pygaul
short_description:
  Easy access to administrative boundary defined by FAO GAUL from
  Python scripts
